name: bam
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - absl-py=2.2.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.16=py312h178313f_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - apptools=5.1.0=pyh44b312d_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - blas=2.131=mkl
  - blas-devel=3.9.0=31_hcf00494_mkl
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - catkin_pkg=1.0.0=pyhd8ed1ab_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - configobj=5.0.9=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h68727a3_0
  - cpuonly=2.0=0
  - cpython=3.12.9=py312hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - distro=1.9.0=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - envisage=7.0.3=pyhff2d567_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=7.1.1=gpl_h0b79d52_704
  - filelock=3.18.0=pyhd8ed1ab_0
  - flatbuffers=24.12.23=h8f4948b_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py312h178313f_0
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.5.0=py312h178313f_1
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gast=0.6.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.84.1=h07242d1_0
  - glib-tools=2.84.1=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h7201bc8_3
  - gnutls=3.7.6=he274497_3
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.1.1=py312h2ec8cdc_1
  - grpcio=1.67.1=py312hacea422_2
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - harfbuzz=11.0.1=h2c12942_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jack=1.9.22=h7c63dc7_2
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jsoncpp=1.9.6=hf42df4d_1
  - kaldi=5.5.1112=cpu_hb028f0a_7
  - keras=3.9.0=pyh753f3f9_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.21.8=h84d6215_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libavif16=1.2.1=hbb36593_2
  - libblas=3.9.0=31_hfdb39a5_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_h372d94f_mkl
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp18.1=18.1.8=default_hb5137d0_8
  - libclang-cpp19.1=19.1.7=default_hb5137d0_2
  - libclang-cpp20.1=20.1.2=default_hb5137d0_0
  - libclang13=20.1.2=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdb=6.2.32=h9c3ff4c_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.67.1=h25350d4_2
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_hc41d3b0_mkl
  - liblapacke=3.9.0=31_hbc6e62b_mkl
  - libllvm15=15.0.7=ha7bfdaf_5
  - libllvm18=18.1.8=ha7bfdaf_3
  - libllvm19=19.1.7=ha7bfdaf_1
  - libllvm20=20.1.2=ha7bfdaf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.0.0=hac27bb2_0
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_0
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_0
  - libopenvino-hetero-plugin=2025.0.0=h3f63f65_0
  - libopenvino-intel-cpu-plugin=2025.0.0=hac27bb2_0
  - libopenvino-intel-gpu-plugin=2025.0.0=hac27bb2_0
  - libopenvino-intel-npu-plugin=2025.0.0=hac27bb2_0
  - libopenvino-ir-frontend=2025.0.0=h3f63f65_0
  - libopenvino-onnx-frontend=2025.0.0=h6363af5_0
  - libopenvino-paddle-frontend=2025.0.0=h6363af5_0
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_0
  - libopenvino-tensorflow-frontend=2025.0.0=h630ec5c_0
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.0=hd9ff511_3
  - libtorch=2.6.0=cpu_mkl_hc5f969b_101
  - libudev1=257.4=hbe16f8c_1
  - libunistring=0.9.10=h7f98852_0
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.9=h84d6215_0
  - libusb=1.0.28=hb9d3cd8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.1=hc4a0caf_0
  - libxml2=2.13.7=h4bc477f_1
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.2=h024ca30_0
  - loguru=0.7.2=py312h7900ff3_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.10.1=py312h7900ff3_0
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - mayavi=4.8.2=noqt_py312h6133e7f_108
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mesalib=25.0.3=he8ffa69_0
  - mkl=2024.2.2=ha957f24_16
  - mkl-devel=2024.2.2=ha770c72_16
  - mkl-include=2024.2.2=ha957f24_16
  - ml_dtypes=0.4.0=py312hf9745cd_2
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py312h68727a3_0
  - multidict=6.3.2=py312h178313f_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_5
  - mysql-connector-python=9.0.0=py312h374181b_1
  - mysql-libs=9.0.1=he0572af_5
  - namex=0.0.8=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.8.1=hc379101_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.11.3=he02047a_1
  - nspr=4.36=h5888daf_0
  - nss=3.110=h159eef7_0
  - numpy=2.2.4=py312h72c5963_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2024.10.24=h5888daf_0
  - openfst=1.8.3=h84d6215_3
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.0=h7b32b05_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.15.0=py312h68727a3_0
  - p11-kit=0.25.3=he72ba39_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_1
  - pango=1.56.3=h9ac818e_1
  - pcre2=10.44=hba22ea6_2
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - ply=3.11=pyhd8ed1ab_3
  - proj=9.5.1=h0054346_0
  - propcache=0.2.1=py312h178313f_1
  - protobuf=5.28.3=py312h2ec8cdc_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hac146a9_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pycparser=2.22=pyh29332c3_1
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - pyside6=6.9.0=py312h91f0f75_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=6_cp312
  - pytorch=2.6.0=cpu_mkl_py312_h446997d_101
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.15=h993ce98_3
  - qt6-main=6.9.0=h6441bc3_0
  - rav1e=0.6.6=he8a937b_2
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rosdep=0.25.1=pyhd8ed1ab_1
  - rosdistro=0.9.0=py312h7900ff3_2
  - rospkg=1.6.0=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py312h7a48858_0
  - scipy=1.15.2=py312ha707e6e_0
  - sdl2=2.32.54=h9b8e6db_0
  - sdl3=3.2.10=h3083f51_0
  - setuptools=78.1.0=pyhff2d567_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - snappy=1.2.1=h8bd8927_1
  - spirv-tools=2024.3=h84d6215_0
  - sqlalchemy=2.0.40=py312h66e93f0_0
  - sqlite=3.49.1=h9eae976_2
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.13.3=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - tensorboard=2.18.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.7.0=py312hda17c39_2
  - tensorflow=2.18.0=cpu_py312h69ecde4_0
  - tensorflow-base=2.18.0=cpu_py312h099d1c6_0
  - tensorflow-estimator=2.18.0=cpu_py312hc0a35a6_0
  - termcolor=3.0.1=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.6.0=cpu_py312hac12bba_1
  - torchvision=0.21.0=cpu_py312_h11dcf35_1
  - torchvision-extra-decoders=0.0.2=py312h4387730_2
  - tornado=6.4.2=py312h66e93f0_0
  - traits=7.0.2=py312h66e93f0_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.13.1=hf5ce1d7_0
  - typing_extensions=4.13.1=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - utfcpp=4.0.6=h005c6e1_0
  - vtk=9.3.1=osmesa_py312hf4758c4_114
  - vtk-base=9.3.1=osmesa_py312h1dc7465_114
  - vtk-io-ffmpeg=9.3.1=osmesa_py312hf4758c4_114
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.42=hd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py312h66e93f0_0
  - wslink=2.3.3=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.3=py312h178313f_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312h66e93f0_1
  - zstd=1.5.7=hb8e6e7a_2
